### ISSUE TITLE
Request: Look for KAS container on part with workshop module first

### ISSUE THREAD

**Issue by Angel-125** [obivandamme/Workshop#2]
This is a great mod and I like how it adds completed parts to a KAS container. But vessels with lots of KAS containers make finding the new part a needle in a haystack. It would be really convenient if the physical part with the 3D printer had a KAS container, and the 3D printer put the completed part in the container unless full, in which case it looks for the first available part in the ship that can hold the part. Confusing, so here is a pseudo config file:

module
{
Name = KASContainer //the 3DPrinter will look for this container first for available space before looking anywhere else in the vessel
...
}

Module
{
Name = 3DPrinter //will look for the above KAS container module to put conpleted parts in before looking elsewhere
...
}

**Comment by obivandamme** [comment]
I have tought about that for a while and have a good idea for implementing that. It will be configurable how the workshop stores it's items

**Comment by obivandamme** [comment]
Mod switched from KAS to KIS and only places items into its own inventory
