### ISSUE TITLE
Add all workshop parts to the same category.

### ISSUE THREAD

**Issue by enceos** [obivandamme/Workshop#24]
Since we decided to make a separate category for Workshop parts in editor, lets fill it with all the parts of this mod, namely containers. Currently I can see only the Mobile Processing Lab and the 3D Printing Lab in there.
P.S. Is there a way to assign a custom icon for this category? I could draw one.

**Comment by obivandamme** [comment]
I did this with the latest patch. Custom icons are not supported at the moment as far as i can see.
