### ISSUE TITLE
Update Required Mods list

### ISSUE THREAD

**Issue by Bear67** [obivandamme/Workshop#27]
Took me a bit to figure out why none of the workshop items were showing up. I don't have RoverDude's OKS/MKS mod installed and your using Model's from the Kolonization/Assets directory.

Or get RoverDude's Permission to include his Model in your Assets Folder. It's not like he doesn't bundle other people's mods with his mods. :)

**Comment by obivandamme** [comment]
The last time i checked there where no dependencies to mks. i will double check but it must be something else. the only dependency is KIS

**Comment by Bear67** [comment]
HA, Might help if I was using the current Workshop build. DUH! My bad.
