### ISSUE TITLE
Recipes balance

### ISSUE THREAD

**Issue by NyankoSensei** [obivandamme/Workshop#28]
The new math price-mass make strange values for some parts, better solution is add exoticminerals and raremetals to all recipes for have a better balance weight-prices

OSE_DefaultRecipe
{
    name = part
    RESOURCES
    {
        MaterialKits = 10
            RareMetals = 1
            ExoticMinerals = 1
    }
}

@PART[*]:HAS[@MODULE[ModuleScienceExperiment]]:FOR[Workshop]
{
    OSE_PartRecipe
    {
        MaterialKits = 10
        RareMetals = 10
        ExoticMinerals = 10
    }
}

@PART[*]:HAS[@MODULE[ModuleCommand]]:FOR[Workshop]
{
    OSE_PartRecipe
    {
        MaterialKits = 10
        RareMetals = 10
        ExoticMinerals = 1
    }
}

@PART[*]:HAS[@MODULE[ModuleEnginesFX]]:FOR[Workshop]
{
    OSE_PartRecipe
    {
        MaterialKits = 10
        RareMetals = 1
        ExoticMinerals = 10
    }
}

**Comment by obivandamme** [comment]
The current default recipes are just to show the concept and to help players to get used to the new resources and build the required infrastructure. There will be a lot more balancing in this part of the mod

**Comment by NyankoSensei** [comment]
I agree, this part need a good balance, but for now mods that use rocketparts are locked waiting for a usable patch, i have wrote 1 mm_patch for usi_mods but i wait for some changes in recipes first to do a pullrequest.

I don't tell those recipes are correct but i think for handle prices and weight without broking gameplay are need all 3 resources for every part (and make sense have a bit of raremetals and exoticminerals for handle electrical and chemical).

Sorry if i'm boring but i really like use this genuine mod in a correct way

Regards
Luca
