### ISSUE TITLE
Paused Production

### ISSUE THREAD

**Issue by Bear67** [obivandamme/Workshop#4]
"The Workshop will put items into its own inventory only. If it is full, the item will be hold in queue and production is paused" - Build notes 0.4.0..

I've added a MM cfg to increase the volume from 2 to 2000, build a part and it pauses on completion. It's not moving it into the inventory.
![screenshot6](https://cloud.githubusercontent.com/assets/5138687/7018864/4cdc2d8a-dccf-11e4-8da4-5aa09f32392b.png)

**Comment by obivandamme** [comment]
I will try to reproduce and tlook at this Issue. Can you please post your MM config?

**Comment by Bear67** [comment]
@PART[OSE_Workshop]:AFTER[KIS]
{
    @MODULE[ModuleKISInventory]
    {
        @maxVolume = 2000
    }
}

**Comment by obivandamme** [comment]
I am currently not able to reproduce this Issue. Did the production on the same Vessel work before? Can you build other Items on the same Vessel? Can you take a look at the Debug menu and post a Screenshot if anyerrors are present?

**Comment by Bear67** [comment]
![screenshot8](https://cloud.githubusercontent.com/assets/5138687/7097794/aa053b38-df9e-11e4-8f97-85d1a8b82991.png)

**Comment by obivandamme** [comment]
Ah ok, the Version of KIS you are using is different from the one I referenced when building 0.4.0 of the Workshop. I will get the latest KIS release and release a compatibility patch asap
